version: '3'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: tut-frontend
    command: serve -s build -l 3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - tut-network

  api: 
    build: ./api
    container_name: tut-api
    command: npm run start
    restart: unless-stopped
    # ports:
    #   - "3001:3001"
    environment:
      - PORT=3001
      # - HOST=http://tut.com
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - tut-network

  auth:
    build: ./auth
    container_name: tut-auth
    command: npm run start
    restart: unless-stopped
    # ports:
    #   - "3002:3002"
    environment:
      - PORT=3002
      # - HOST=http://auth.tut.com
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001/api
    networks:
      - tut-network

  api_db:
    image: mongo:latest
    container_name: tut-api-db
    volumes: 
      - mongodb_api:/data/api
    depends_on:
      - auth_db
    networks:
      - tut-network

  auth_db:
    image: mongo:latest
    container_name: tut-auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - tut-network

  nginx:
    image: nginx:stable-alpine
    container_name: tut-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth
    networks:
      - tut-network

volumes:
  mongodb_api:
  mongodb_auth:

networks:
  tut-network:
    driver: bridge